// GENERATED by build-core.mjs from ../index.html — do not edit by hand.
// Source of truth: the /*__SETBOOK_MCP_CORE_*__*/ regions in index.html.
// Rebuild after app changes: node build-core.mjs


/* NOTE (MCP core): this region is extracted verbatim into
   setbook-mcp/core/setbook-core.mjs by setbook-mcp/build-core.mjs. Keep it
   environment-agnostic — no app state, no DOM beyond DOMParser/fetch — so
   the app and the MCP server parse identically. */
function uid(prefix){ return prefix + '_' + Math.random().toString(36).slice(2,9); }


/* NOTE (MCP core): this region is extracted verbatim into
   setbook-mcp/core/setbook-core.mjs by setbook-mcp/build-core.mjs. Keep it
   environment-agnostic — no app state, no DOM beyond DOMParser/fetch — so
   the app and the MCP server parse identically. */
const SECTION_TYPES = [
  { id:'intro', label:'Intro' },
  { id:'verse', label:'Verse' },
  { id:'chorus', label:'Chorus' },
  { id:'pre-chorus', label:'Pre-Chorus' },
  { id:'bridge', label:'Bridge' },
  { id:'instrumental', label:'Instrumental' },
  { id:'outro', label:'Outro' },
  { id:'custom', label:'Custom' },
];
// A custom name that is really a section-type name, optionally with a
// trailing number ("Chorus", "chorus 2", "PRE-CHORUS"). Returns the type id,
// or null. Matching is case-insensitive and ignores extra whitespace; the
// typed number is discarded because the app owns numbering.
function sectionTypeFromCustomName(text){
  const norm = (text || '').trim().toLowerCase().replace(/\s+/g, ' ');
  if (!norm) return null;
  const m = norm.match(/^(intro|verse|chorus|pre[-\s]?chorus|bridge|instrumental|outro)(\s*\d+)?$/);
  if (!m) return null;
  return m[1].replace(/\s+/, '-');
}
function sectionBaseName(sec){
  if (!sec) return '';
  if (sec.nameType && sec.nameType !== 'custom'){
    const t = SECTION_TYPES.find(t => t.id === sec.nameType);
    if (t) return t.label;
    // retired type id (e.g. removed from the picker in a later version):
    // prettify the id itself rather than showing "Untitled section"
    return sec.nameType.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  }
  return (sec.customName || '').trim();
}


/* NOTE (MCP core): this region is extracted verbatim into
   setbook-mcp/core/setbook-core.mjs by setbook-mcp/build-core.mjs. Keep it
   environment-agnostic — no app state, no DOM beyond DOMParser/fetch — so
   the app and the MCP server parse identically. */
const DEGLUE_CHORD_SRC = '[A-G][#b]?(?:m(?!aj)|maj|min|dim|aug|sus|add)?\\d*(?:[#b]\\d+)?(?:sus[24])?(?:\\/[A-G][#b]?)?';
const DEGLUE_CHORD_RE = new RegExp('^(?:' + DEGLUE_CHORD_SRC + ')$');
const DEGLUE_LEAD_RE = new RegExp('^(' + DEGLUE_CHORD_SRC + ')(?=[A-Z])');
const DEGLUE_MID_RE = new RegExp('([ \\t])(' + DEGLUE_CHORD_SRC + ')(?=[A-Z])', 'g');
const DEGLUE_TRAIL_GLUED_RE = new RegExp('([a-z])(' + DEGLUE_CHORD_SRC + ')$');
/* Chord glued straight after sentence punctuation: "salt,A7Put",
   "dollar,C C# D". The lookahead allows a glued capital, whitespace (a
   chord run), or end of line — digits ("3,000") and lowercase words
   ("St.George") never qualify, so commas inside numbers and
   abbreviations stay whole. */
const DEGLUE_PUNCT_RE = new RegExp('([,;:.!?])(' + DEGLUE_CHORD_SRC + ')(?=[\\s(]|[A-Z]|$)', 'g');
/* Chord (with something beyond its root letter — A7, F#m, Bbsus, D/F#…)
   glued to a lowercase lyric word at line start: "A7joo-ba". The token
   must contain a digit, accidental, quality word, or slash — bare
   root+quality glue ("Am…") stays put, so ordinary words beginning with
   chord prefixes ("Amazing", "Email") never split. */
const DEGLUE_LEAD_LOWER_RE = new RegExp('^(' + DEGLUE_CHORD_SRC + ')(?=[a-z])');
function deglueLeadLowerIsRealChord(tok){
  return /[0-9#b]\/?|maj|min|dim|aug|sus|add|\//.test(tok);
}
/* Longest chord prefix of a line, for the lowercase-glue rule. Backtracking
   the regex with a lowercase lookahead would happily match a NON-maximal
   prefix ("E7sus4" -> "E7" + "s…"), shredding real slash/extension chords —
   so we match greedily first and only then ask what follows. */
const DEGLUE_CHORD_PREFIX_RE = new RegExp('^(' + DEGLUE_CHORD_SRC + ')');
/* A chord tail token, optionally wrapped in bar pipes: "D7", "|D7". */
const DEGLUE_TAIL_TOK_RE = new RegExp('^\\|*(?:' + DEGLUE_CHORD_SRC + ')\\|*$');

// A line ending in whitespace-separated chord tokens after lyric text gets
// its chord tail moved to its own line: "…Arizona   D   C" -> "…Arizona" /
// "D   C". Bar-pipe tokens count ("…walkin' out   |D7"). Pure chord lines
// (and bar grids) are returned unchanged.
function deglueTrailingTail(line){
  const parts = line.split(/([ \t]+)/);
  let cut = parts.length;
  while (cut > 0){
    const t = parts[cut - 1];
    if (/^[ \t]+$/.test(t) || DEGLUE_TAIL_TOK_RE.test(t)) cut--;
    else break;
  }
  if (cut === 0 || cut === parts.length) return null;
  const head = parts.slice(0, cut).join('').replace(/[ \t]+$/, '');
  const tail = parts.slice(cut).join('').replace(/^[ \t]+/, '');
  if (!head || !tail) return null;
  const headHasLyric = head.split(/[ \t]+/).some(tok => tok && !DEGLUE_TAIL_TOK_RE.test(tok));
  if (!headHasLyric) return null;
  return [head, tail];
}

/* A leading run of chord tokens (and bar pipes / xN markers) followed by
   lyric text splits after the run: "C C# D   Take a silver dime" ->
   "C C# D" / "Take a silver dime". A run of a single root-only chord
   ("A Letter…") does not split — ordinary sentences starting with the
   letters A–G must stay whole. Pure chord lines have no remainder and
   are untouched. */
function deglueLeadingChordRun(line){
  const parts = line.split(/([ \t]+)/);
  let idx = 0, chords = 0, sawStrong = false;
  while (idx < parts.length){
    const t = parts[idx];
    if (t === '' || /^[ \t]+$/.test(t)){ idx++; continue; }
    if (/^\|+$/.test(t) || /^x\d+$/i.test(t)){ idx++; continue; }
    if (DEGLUE_CHORD_RE.test(t)){
      chords++;
      if (t.length > 1) sawStrong = true;
      idx++;
      continue;
    }
    break;
  }
  if (!chords) return null;
  const rest = parts.slice(idx).join('');
  // Only split when lyric text actually follows the run (a pure chord
  // line — possibly with trailing pipes — has none), and never split a
  // lone root-only chord off the front of a sentence.
  if (!rest || !/^[A-Za-z(]/.test(rest)) return null;
  if (chords < 2 && !sawStrong) return null;
  return [parts.slice(0, idx).join('').replace(/[ \t]+$/, ''), rest];
}function deglueChordLyricLines(text){
  const out = [];
  (text || '').split('\n').forEach(rawLine => {
    // 0. Chord glued straight after punctuation: "salt,A7Put" ->
    //    "salt," / "A7Put"; "dollar,C C# D" -> "dollar," / "C C# D".
    let pieces = rawLine.replace(DEGLUE_PUNCT_RE, '$1\n$2').split('\n');
    // 1. Leading chord glued to a lyric word: "GSlowin'" -> "G" / "Slowin'".
    // The uppercase-next-letter rule keeps lyric words like "Amazing" whole.
    pieces = pieces.flatMap(p => {
      const segs = [];
      let rest = p, guard = 0;
      while (guard++ < 8){
        const m = rest.match(DEGLUE_LEAD_RE);
        if (!m) break;
        segs.push(m[1]);
        rest = rest.slice(m[1].length);
      }
      segs.push(rest);
      return segs;
    });
    // 1b. Leading chord with real content (A7, F#m, Bbsus…) glued to a
    //     lowercase word: "A7joo-ba" -> "A7" / "joo-ba…". The longest chord
    //     prefix wins, so "E7sus4" / "F#7sus4" (whose next letter is merely
    //     the chord's own "sus") stay whole; bare root+quality glue
    //     ("Amazing", "Email") never splits.
    pieces = pieces.flatMap(p => {
      const m = p.match(DEGLUE_CHORD_PREFIX_RE);
      if (!m) return [p];
      const rest = p.slice(m[1].length);
      if (!/^[a-z]/.test(rest)) return [p];
      if (!deglueLeadLowerIsRealChord(m[1])) return [p];
      return [m[1], rest];
    });
    // 2. Mid-line: chord glued to the next lyric word: "D   CSuch" -> "D   C" / "Such".
    pieces = pieces.flatMap(p => p.replace(DEGLUE_MID_RE, '$1$2\n').split('\n'));
    // 2b. Leading chord run followed by lyric: "C C# D   Take a silver dime"
    //     -> "C C# D" / "Take a silver dime".
    pieces = pieces.flatMap(p => deglueLeadingChordRun(p) || [p]);
    // 3. Trailing: chord glued to a lyric ending ("mindG") or a chord tail
    //    (including bar-pipe tokens, "…walkin' out   |D7") moves to its own line.
    pieces = pieces.flatMap(p => {
      const g = p.match(DEGLUE_TRAIL_GLUED_RE);
      const lines = g ? [p.slice(0, g.index + 1), g[2]] : [p];
      return lines.flatMap(l => deglueTrailingTail(l) || [l]);
    });
    out.push(...pieces);
  });
  return out.join('\n');
}

function normalizeScrapedText(text){
  const cleaned = (text || '').replace(/\r\n?/g, '\n').replace(/\u00a0/g, ' ').split('\n')
    .map(l => l.replace(/[ \t\u00a0]+$/, ''))
    .join('\n')
    .replace(/^\n+|\n+$/g, '')
    .replace(/\n{3,}/g, '\n\n');
  return deglueChordLyricLines(cleaned.split('\n').map(breakOutInlineSectionHeaders).join('\n'));
}

/* Tab sites glue [Verse 1]-style headers into the lines around them
   ("…much too slow.  [Verse 2]E7sus4"), which hides them from the
   mass-entry auto-split — it only reads headers that sit alone on a line.
   Recognized headers (same mapping the splitter uses) are broken out onto
   their own lines before deglue runs; unrecognized [Text] stays inline. */
function breakOutInlineSectionHeaders(line){
  const re = /\[([^\[\]]+)\]/g;
  const parts = [];
  let last = 0, m, found = false;
  while ((m = re.exec(line))){
    if (!massHeaderSectionType(m[1])) continue;
    found = true;
    const before = line.slice(last, m.index).replace(/[ \t]+$/, '');
    if (before) parts.push(before);
    parts.push(m[0]);
    last = m.index + m[0].length;
  }
  if (!found) return line;
  const rest = line.slice(last).replace(/^[ \t]+/, '');
  if (rest) parts.push(rest);
  return parts.join('\n');
}

const MASS_BLOCK_TAGS = new Set(['P','DIV','LI','TR','H1','H2','H3','H4','H5','H6','PRE','BLOCKQUOTE','SECTION','ARTICLE','HR','TABLE','UL','OL','DT','DD','FIGCAPTION']);
function extractTextFromHtml(htmlText){
  // DOMParser never executes scripts — this is pure text extraction.
  const doc = new DOMParser().parseFromString(htmlText, 'text/html');
  doc.querySelectorAll('script,style,noscript,template,nav,header,footer,aside,form,iframe').forEach(el => el.remove());
  const out = [];
  const walk = (node) => {
    node.childNodes.forEach(ch => {
      if (ch.nodeType === 3){ out.push(ch.textContent); }
      else if (ch.nodeType === 1){
        if (ch.tagName === 'BR'){ out.push('\n'); return; }
        const block = MASS_BLOCK_TAGS.has(ch.tagName);
        if (block) out.push('\n');
        walk(ch);
        if (block) out.push('\n');
      }
    });
  };
  walk(doc.body || doc);
  return normalizeScrapedText(out.join(''));
}

async function fetchUrlText(rawUrl){
  const input = (rawUrl || '').trim();
  if (!input) throw new Error('Enter a URL first.');
  // Resolve first, then gate the scheme on the resolved URL: WHATWG URL
  // parsing strips tabs/newlines, so checking the raw string is not enough.
  let url;
  try {
    url = new URL(/^[a-z][a-z0-9+.-]*:/i.test(input) ? input : 'https://' + input);
  } catch(e){
    throw new Error('That URL doesn\u2019t look valid.');
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') throw new Error('Only http(s) URLs are supported.');
  let res;
  try {
    res = await fetch(url.toString());
  } catch(e){
    // The fetch itself rejected: a network failure or, far more often, the
    // site blocking the cross-origin read. Flag it so the dialog can point
    // the user at the scraper extension.
    const err = new Error('Couldn\u2019t read text from that URL.');
    err.isCorsBlock = true;
    throw err;
  }
  if (!res.ok) throw new Error('The server answered ' + res.status + '.');
  const ct = (res.headers.get('content-type') || '').toLowerCase();
  const body = await res.text();
  if (ct.includes('text/html') || /<\s*html[\s>]/i.test(body.slice(0, 4000))) return extractTextFromHtml(body);
  return normalizeScrapedText(body);
}

/* Mass-entry staging rows are chord-over-lyric pairs, like section editor rows:
   { chords, text }. On import, lines that look like chord lines land in the
   chord box automatically; everything else lands in the lyric box. */
const MASS_CHORD_TOKEN_RE = /^[A-G][#b]?(?:m(?!aj)|maj|min|dim|aug|sus|add)?\d*[#b]?(?:sus|add)?\d*(?:\/[A-G][#b]?)?$/;
function asMassPair(p){
  if (p && typeof p === 'object') return { chords: p.chords || '', text: p.text || '' };
  return { chords: '', text: (p == null ? '' : String(p)) };
}
/* Chord-diagram lines from tab sites (e.g. "Am7/G     302013") carry chord
   fingerings, not song content — dropped on import. */
function looksLikeChordDiagramLine(line){
  const t = (line || '').trim();
  if (!/[\dxX]{6}\s*$/.test(t)) return false;
  const core = t.replace(/[\dxX]{6}\s*$/, '').trim();
  return !!core && core.split(/\s+/).every(tok => MASS_CHORD_TOKEN_RE.test(tok));
}

/* Section-header lines from tab sites: "[Verse 1]" -> verse, "[Chorus]" ->
   chorus, etc. "[Solo]"/"[Interlude]" map to instrumental. */
function massHeaderSectionType(headerText){
  const mapped = sectionTypeFromCustomName(headerText);
  if (mapped) return mapped;
  const norm = (headerText || '').trim().toLowerCase();
  if (norm === 'solo' || norm === 'interlude') return 'instrumental';
  return null;
}

/* Per-line classification of mass-entry text, shared by the live preview
   overlay and the Create-sections parse so the preview can never lie about
   what the parse will do. Strict alternation by position, like the + Enter
   multiple lines box: the first content line of the text (and of each
   [Section]) is a chord line; chord and lyric lines alternate after that.
   Each raw line classifies as:
   - 'header': a [Section] line, which starts a new section (a recognized
     name maps to a typed section; any other [Name] becomes a custom-named
     section). Headers reset the alternation and don't consume a position.
   - 'dropped': chord-diagram lines (and their Chords: introducer) — removed
   - 'chord' / 'lyric': by position among the remaining lines; a trailing xN
     on a chord line still becomes SetBook's (xN) shorthand
   - null: blank lines, which are separators, not rows */
function massTrimChunkEnds(t){
  return (t || '').replace(/^(?:[ \t\u00a0]*\n)+/, '').replace(/(?:\n[ \t\u00a0]*)+$/, '');
}

function autoSplitMassFields(sec){
  const fields = sec.massEntryFields || [];
  const out = [];
  let created = 0;
  fields.forEach((field) => {
    const lines = (field.text || '').split('\n');
    const chunks = [];
    let chunk = [];
    let chunkType = field.nameType;
    const flushChunk = () => {
      chunks.push({ text: massTrimChunkEnds(chunk.join('\n')), nameType: chunkType });
      chunk = [];
    };
    lines.forEach((line) => {
      const hm = line.match(/^\[(.+)\]$/);
      const mapped = hm ? massHeaderSectionType(hm[1]) : null;
      if (mapped){ flushChunk(); chunkType = mapped; }
      else chunk.push(line);
    });
    flushChunk();
    const kept = chunks.filter(c => c.text !== '');
    const final = kept.length ? kept : chunks.slice(0, 1);
    final.forEach((c, i) => {
      // The first chunk continues the original field, so it keeps its name;
      // later chunks start fresh.
      out.push({ id: i === 0 ? field.id : uid('mf'), text: c.text, nameType: c.nameType,
        customName: i === 0 ? (field.customName || '') : '',
        nameSuffix: i === 0 ? (field.nameSuffix || '') : '' });
    });
    created += final.length - 1;
  });
  sec.massEntryFields = out;
  return created;
}

function massLineTokens(t){
  return t.split(/[ \t\u00a0]+/).filter(Boolean);
}
// A token counts as chord-side when it's a chord symbol, a bar separator,
// or an xN repeat marker.
function massTokIsChordish(tok){
  return DEGLUE_CHORD_RE.test(tok) || /^\|+$/.test(tok) || /^x\d+$/i.test(tok);
}

/* roles (optional): per-line overrides parallel to text's lines — 'chord'
   or 'lyric' force a line's kind (the swap buttons in the mass-style editor);
   null/undefined keeps the automatic classification. An explicit role also
   rescues the line from chord-diagram dropping. */
function classifyMassEntryLines(text, roles){
  const rawLines = (text || '').split('\n');
  let expectChord = true; // top row of each field is chords
  return rawLines.map((rawLine, idx) => {
    const t = (rawLine || '').replace(/[ \t\u00a0]+$/, '');
    if (t.trim() === '') return { line: rawLine, type: null };
    const forced = roles && (roles[idx] === 'chord' || roles[idx] === 'lyric') ? roles[idx] : null;
    if (!forced){
      if (/^chords:\s*$/i.test(t)){
        const next = rawLines.slice(idx + 1).find(l => (l || '').trim() !== '');
        if (next && looksLikeChordDiagramLine(next)) return { line: rawLine, type: 'dropped' };
      }
      if (looksLikeChordDiagramLine(t)) return { line: rawLine, type: 'dropped' };
    }
    // Content-aware classification: an unambiguous chord line is chords even
    // in lyric position (and vice versa), so deglued imports and doubled
    // lines (two chord lines or two lyric lines in a row) can't flip the
    // phase for everything below them. Ambiguous lines (a lone "Am", exotic
    // chord spellings) fall back to strict positional alternation.
    const toks = massLineTokens(t);
    const isChordLine = toks.length > 0 && toks.every(massTokIsChordish);
    const isLyricLine = toks.some(tok => /[a-z]/.test(tok) && !massTokIsChordish(tok));
    const type = forced || (isChordLine ? 'chord' : (isLyricLine ? 'lyric' : (expectChord ? 'chord' : 'lyric')));
    expectChord = (type !== 'chord');
    const forcedFlag = !!forced;
    if (type === 'lyric') return { line: rawLine, type, text: t, forced: forcedFlag };
    // Role-forced lines are the user's own chord text (swap buttons and
    // pre-seeded roles): keep it verbatim — no xN→(xN) shorthand rewrite.
    if (forced) return { line: rawLine, type, chords: t, forced: true };
    const repM = t.match(/(?:^|\s)x(\d+)\s*$/);
    const repN = repM ? repM[1] : null;
    const core = repN ? t.slice(0, repM.index).replace(/[ \t\u00a0]+$/, '') : t;
    return { line: rawLine, type, repN, forced: forcedFlag,
      chords: repN ? (core ? core + ' (x' + repN + ')' : '(x' + repN + ')') : t };
  });
}

/* Split mass-entry text into section blocks. The classifier already put
   every content line on strict chord/lyric alternation, so each chord line
   pairs with the lyric line under it into a single chord-over-lyric row; a
   chord line at the end of a section (or before a header) is a chord-only
   row. [Section] headers start a new typed (or custom-named) block; dropped
   lines and blank lines never become rows. */
function parseMassFieldRows(text, roles){
  const rows = [];
  const items = [];
  let pendingBlank = false;
  classifyMassEntryLines(text, roles).forEach(c => {
    if (c.type === 'dropped') return; // dropped lines neither pair nor separate
    if (c.type === null){ pendingBlank = true; return; }
    if (c.type === 'chord') items.push({ kind: 'chord', chords: c.chords, repN: c.repN, gapBefore: pendingBlank, forced: !!c.forced });
    else items.push({ kind: 'lyric', text: c.text, gapBefore: pendingBlank, forced: !!c.forced });
    pendingBlank = false;
  });
  for (let i = 0; i < items.length; i++){
    const it = items[i];
    /* A chord line pairs with the lyric line under it. For role-forced
       chords (the mass-style editor's own rows), a blank line between the
       chord and its lyric deliberately leaves the chord unpaired — that's
       how a chords-only row round-trips through the text representation. A
       blank *before* the chord is just row spacing and never affects pairing.
       For automatic classification (URL import), blank lines never disturb
       the pairing — legacy mass-entry behavior. */
    if (it.kind === 'chord' && !(it.forced && i + 1 < items.length && items[i + 1].gapBefore) && i + 1 < items.length && items[i + 1].kind === 'lyric'){
      const lyricText = items[i + 1].text;
      rows.push({ chords: it.chords, text: it.repN ? lyricText + ' (x' + it.repN + ')' : lyricText });
      i++;
    } else if (it.kind === 'chord'){
      rows.push({ chords: it.chords, text: it.repN ? '(x' + it.repN + ')' : '' });
    } else {
      rows.push({ chords: '', text: it.text });
    }
  }
  return rows;
}

/* Tab-site formatting for the mass-entry import: a recognized [Section]
   header buried mid-line (e.g. "last lyric [Chorus] Em C") is split onto its
   own line, so it becomes a section break instead of staying glued to lyric
   text. Headers already alone on a line are left untouched, and unrecognized
   [bracketed] text is never split (lyrics can contain brackets). */
function massSplitDefaultType(nameType){
  switch (nameType){
    case 'verse': return 'chorus';
    case 'chorus':
    case 'bridge':
    case 'instrumental': return 'verse';
    case 'pre-chorus': return 'chorus';
    default: return 'verse';
  }
}


/* NOTE (MCP core): this region is extracted verbatim into
   setbook-mcp/core/setbook-core.mjs by setbook-mcp/build-core.mjs. Keep it
   environment-agnostic — no app state, no DOM beyond DOMParser/fetch — so
   the app and the MCP server parse identically. */
function parseChordLine(str){
  const symbols = [];
  const re = /\S+/g;
  let m;
  while ((m = re.exec(str)) !== null){
    symbols.push({ pos: m.index, value: m[0] });
  }
  return symbols;
}

export {
  uid,
  SECTION_TYPES,
  sectionTypeFromCustomName,
  sectionBaseName,
  fetchUrlText,
  extractTextFromHtml,
  normalizeScrapedText,
  deglueChordLyricLines,
  classifyMassEntryLines,
  parseMassFieldRows,
  parseChordLine,
  autoSplitMassFields,
  massHeaderSectionType,
  massSplitDefaultType
};
