#!/usr/bin/env node
/* Build the MCP core module from the SetBook app.
   The app's index.html is the source of truth: the marked MCP-core regions
   in index.html are extracted verbatim (in document order) and written to
   core/setbook-core.mjs with an export list appended.

   Run after any app change that touches the marked regions:
       node build-core.mjs
   test-core.mjs fails if the checked-in core no longer matches a fresh
   extraction, so a stale core can never ship silently.
*/
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
// Repo layout: setbook-mcp/ sits next to index.html. Override with
//   node build-core.mjs /path/to/index.html
// when building from a different checkout. Pass --stdout to print the
// module instead of writing core/setbook-core.mjs (used by the parity test).
const args = process.argv.slice(2);
const APP_HTML = args.find((a) => !a.startsWith('--')) || join(here, '..', 'index.html');
const TO_STDOUT = args.includes('--stdout');
const OUT_FILE = join(here, 'core', 'setbook-core.mjs');

// Names the MCP server (and its tests) may import from the core. Everything
// else extracted stays module-private. Keep this list in sync with what
// song-tools.mjs and test-core.mjs actually use.
const EXPORTS = [
  'uid',
  'SECTION_TYPES',
  'sectionTypeFromCustomName',
  'sectionBaseName',
  'fetchUrlText',
  'extractTextFromHtml',
  'normalizeScrapedText',
  'deglueChordLyricLines',
  'classifyMassEntryLines',
  'parseMassFieldRows',
  'parseChordLine',
  'autoSplitMassFields',
  'massHeaderSectionType',
  'massSplitDefaultType',
];

const html = readFileSync(APP_HTML, 'utf8');
// Only look inside inline <script> blocks: the docs mention the marker
// names in prose, and those must never match.
const scripts = [...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)].map((m) => m[1]);
const re = /\/\*__SETBOOK_MCP_CORE_BEGIN__\*\/([\s\S]*?)\/\*__SETBOOK_MCP_CORE_END__\*\//g;
const regions = [];
for (const src of scripts) {
  let m;
  while ((m = re.exec(src))) regions.push(m[1]);
}
if (!regions.length) {
  console.error('build-core: no marked regions found in ' + APP_HTML);
  process.exit(1);
}

const header = `// GENERATED by build-core.mjs from ../index.html — do not edit by hand.\n` +
  `// Source of truth: the /*__SETBOOK_MCP_CORE_*__*/ regions in index.html.\n` +
  `// Rebuild after app changes: node build-core.mjs\n\n`;

const body = regions.join('\n');
const footer = `\nexport {\n${EXPORTS.map(n => '  ' + n).join(',\n')}\n};\n`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
const output = header + body + footer;
if (TO_STDOUT) {
  process.stdout.write(output);
} else {
  writeFileSync(OUT_FILE, output);
  console.log(`build-core: wrote ${OUT_FILE} (${regions.length} regions, ${EXPORTS.length} exports)`);
}
